apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  version: 7.17.3
  count: 1
  elasticsearchRef:
    name: elasticsearch
  podTemplate:
      spec:
        containers:
        - name: kibana
          imagePullPolicy: Never