version: '3.8'
services:
  registry:
    image: registry:2
    container_name: registry
    volumes:
      - "/mnt/registry:/var/lib/registry"
      - "./registry-config/simple.yml:/etc/docker/registry/config.yml"
    ports:
      - "5001:5000"
    restart: always
    networks:
      - registry-ui-net
  docker-registry-ui:
    image: joxit/docker-registry-ui
    container_name: registry-ui
    ports:
      - "8085:80"
    environment:
      - REGISTRY_TITLE=local registry
      - REGISTRY_URL=http://localhost:5001
      - REGISTRY_PROTOCOL=http
      - SINGLE_REGISTRY=true
    depends_on:
      - registry
    networks:
      - registry-ui-net
networks:
  registry-ui-net: