version: '3.8'
services:
  registry:
    image: registry:2
    container_name: registry
    ports:
      - "5001:5000"
    restart: always
    volumes:
      - "./registry-config/regconfig.yml:/etc/docker/registry/config.yml"
      - "/mnt/registry:/var/lib/registry"
    networks:
      - reg-network
  docker-registry-ui:
    image: joxit/docker-registry-ui
    container_name: reg-ui
    depends_on:
      - registry
    ports:
      - "9070:80"
    environment:
      - REGISTRY_URL=http://localhost:5001
      - REGISTRY_TITLE=local registry
      - REGISTRY_PROTOCOL=http
      - SINGLE_REGISTRY=true
    networks:
      - reg-network
networks:
  reg-network: