apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-conf
data:
  host: mongodb-service
  dbname: exam
  authSource: admin
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: hamdaneyassine/project:backendv2.0
          ports:
            - containerPort: 5000
              name: backend-port
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongodb-conf
                  key: host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mongodb-conf
                  key: dbname
            - name: AUTH_SOURCE
              valueFrom:
                configMapKeyRef:
                  name: mongodb-conf
                  key: authSource
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: password
