apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-conf
data:
  host: mongodb-service
  dbname: exam
  authSource: admin
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backendservice.name }}
spec:
  selector:
    app: {{ .Values.backendselector.matchLabels }}
  ports:
    - port: {{ .Values.backendservice.port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Values.backenddeployment.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.backendselector.matchLabels }}
  template:
    metadata:
      labels:
        app: {{ .Values.backendselector.matchLabels }}
    spec:
      containers:
        - name: backend
          image: hamdaneyassine/project:backendv2.0
          ports:
            - containerPort: 5000
              name: backend-port
          livenessProbe:
            httpGet:
              port: backend-port
              path: /health
            failureThreshold: 1
            periodSeconds: 10
          startupProbe:
            httpGet:
              port: backend-port
              path: /health
            failureThreshold: 30
            periodSeconds: 15
          readinessProbe:
            httpGet:
              port: backend-port
              path: /ready
            failureThreshold: 1
            periodSeconds: 10
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongodb-conf
                  key: host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mongodb-conf
                  key: dbname
            - name: AUTH_SOURCE
              valueFrom:
                configMapKeyRef:
                  name: mongodb-conf
                  key: authSource
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: password
