apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - name: backend-port
      port: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: hamdaneyassine/project:backendv20
          ports:
            - name: backend-port
              containerPort: 5000
          livenessProbe:
            httpGet:
              port: backend-port
              path: /health
            failureThreshold: 1
            periodSeconds: 10
          startupProbe:
            httpGet:
              port: backend-port
              path: /health
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              port: backend-port
              path: /ready
            failureThreshold: 1
            periodSeconds: 10
          env:
            - name: CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: mongodbcluster-admin-hamdane
                  key: connectionString.standard
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-sm
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: backend
  endpoints:
  - port: backend-port