---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodbcluster
spec:
  members: 2
  type: ReplicaSet
  version: "4.2.9"
  prometheus:
    username: prometheusmongo
    passwordSecretRef:
      name: metrics-endpoint-password
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: hamdane
      db: admin
      passwordSecretRef:
        name: userpassword
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
        - name: readWriteAnyDatabase
          db: admin
        - name: root
          db: admin
      scramCredentialsSecretName: my-scram
  statefulSet:
    spec:
      template:
        spec:
          containers:
            - name: mongodb-agent
              readinessProbe:
                failureThreshold: 50
                initialDelaySeconds: 10
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
---
apiVersion: v1
kind: Secret
metadata:
  name: userpassword
type: Opaque
stringData:
  password: hamdane2022
---
apiVersion: v1
kind: Secret
metadata:
  name: metrics-endpoint-password
  namespace: exam
type: Opaque
stringData:
  password: hamdane2022
  username: prometheusmongo

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
  labels:
    release: prometheus

  name: mongodb-sm
  namespace: exam
spec:
  endpoints:
  - basicAuth:
      password:
        key: password
        name: metrics-endpoint-password
      username:
        key: username
        name: metrics-endpoint-password
    port: prometheus
    scheme: http
  namespaceSelector:
    matchNames:
    - exam
  selector:
    matchLabels:
      app: mongodbcluster-svc
